Traceback (most recent call last):
  File "main.py", line 155, in help
WindowsError: [Error 2] : 'help.chm'
